apiVersion: v1
kind: Namespace
metadata:
  name: zeroday-platform
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zeroday-config
  namespace: zeroday-platform
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "zeroday_db"
  MONGO_URI: "mongodb://mongo:27017"
  MONGO_DB_NAME: "zeroday_docs"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  NEXT_PUBLIC_API_URL: "http://backend:8000/api/v1"
